# netlify.toml
[build]
  publish = "." # Your static files (index.html, etc.) are in the root
  functions = "netlify/functions" # Directory for Netlify functions

[functions]
  node_bundler = "esbuild" # Use esbuild for faster bundling

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200